import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase.js'

const styles = {
  page: {
    maxWidth: '800px',
    margin: '0 auto',
    padding: '64px 32px',
  },
  eyebrow: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: '11px',
    fontWeight: '500',
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    color: '#B07D62',
    marginBottom: '16px',
  },
  headline: {
    fontFamily: "'Cormorant Garamond', serif",
    fontSize: 'clamp(36px, 5vw, 56px)',
    fontWeight: '500',
    color: '#1A1A1A',
    marginBottom: '8px',
    lineHeight: '1.1',
  },
  sub: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: '14px',
    fontWeight: '300',
    color: '#6B6560',
    marginBottom: '56px',
    lineHeight: '1.6',
  },
  divider: {
    height: '1px',
    backgroundColor: '#E8E4DE',
    margin: '48px 0',
  },
  sectionTitle: {
    fontFamily: "'Cormorant Garamond', serif",
    fontSize: '28px',
    fontWeight: '500',
    color: '#1A1A1A',
    marginBottom: '24px',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  row: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '16px',
  },
  fieldGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  label: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: '11px',
    fontWeight: '500',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: '#6B6560',
  },
  input: {
    width: '100%',
    padding: '12px 16px',
    fontFamily: "'DM Sans', sans-serif",
    fontSize: '14px',
    fontWeight: '300',
    color: '#1A1A1A',
    backgroundColor: '#F2EEE9',
    border: '1px solid #E8E4DE',
    borderRadius: '2px',
    outline: 'none',
    boxSizing: 'border-box',
  },
  textarea: {
    width: '100%',
    padding: '12px 16px',
    fontFamily: "'DM Sans', sans-serif",
    fontSize: '14px',
    fontWeight: '300',
    color: '#1A1A1A',
    backgroundColor: '#F2EEE9',
    border: '1px solid #E8E4DE',
    borderRadius: '2px',
    outline: 'none',
    boxSizing: 'border-box',
    resize: 'vertical',
    minHeight: '100px',
    lineHeight: '1.6',
  },
  select: {
    width: '100%',
    padding: '12px 16px',
    fontFamily: "'DM Sans', sans-serif",
    fontSize: '14px',
    fontWeight: '300',
    color: '#1A1A1A',
    backgroundColor: '#F2EEE9',
    border: '1px solid #E8E4DE',
    borderRadius: '2px',
    outline: 'none',
    boxSizing: 'border-box',
  },
  button: {
    padding: '14px 32px',
    fontFamily: "'DM Sans', sans-serif",
    fontSize: '13px',
    fontWeight: '500',
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    color: '#FAF8F5',
    backgroundColor: '#1A1A1A',
    border: 'none',
    borderRadius: '2px',
    cursor: 'pointer',
    alignSelf: 'flex-start',
  },
  signOutBtn: {
    padding: '8px 20px',
    fontFamily: "'DM Sans', sans-serif",
    fontSize: '12px',
    fontWeight: '400',
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    color: '#6B6560',
    backgroundColor: 'transparent',
    border: '1px solid #E8E4DE',
    borderRadius: '2px',
    cursor: 'pointer',
  },
  topRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '8px',
  },
  success: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: '13px',
    color: '#27AE60',
    backgroundColor: '#EDFAF3',
    padding: '12px 16px',
    borderRadius: '2px',
    border: '1px solid #B7EAD0',
  },
  error: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: '13px',
    color: '#C0392B',
    backgroundColor: '#FDF0EE',
    padding: '12px 16px',
    borderRadius: '2px',
    border: '1px solid #F5C6C0',
  },
  notAuth: {
    textAlign: 'center',
    padding: '120px 32px',
  },
  notAuthHeadline: {
    fontFamily: "'Cormorant Garamond', serif",
    fontSize: '36px',
    fontStyle: 'italic',
    color: '#1A1A1A',
    marginBottom: '16px',
  },
  notAuthSub: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: '14px',
    fontWeight: '300',
    color: '#6B6560',
    marginBottom: '32px',
  },
  notAuthBtn: {
    display: 'inline-block',
    padding: '14px 32px',
    fontFamily: "'DM Sans', sans-serif",
    fontSize: '13px',
    fontWeight: '500',
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    color: '#FAF8F5',
    backgroundColor: '#1A1A1A',
    borderRadius: '2px',
  },
}

const emptyEvent = {
  title: '',
  venue: '',
  address: '',
  city: '',
  country: '',
  date: '',
  time: '',
  genre: '',
  description: '',
